from seqdiag import diagparser, builder, DiagramDraw
from block.views import show, edit

default_page = "QlpoOTFBWSZTWSLcEJkAAObfgEAQUAOADwKh3Ao+59/KMAD1tYJKRtU8k9RkHqANADTT1BIkUAyABoA0DR6gVSRA0ZNADQaABojAvzJx3iRERMo0El6TQVikjcE1aJo6jLmExpLsmb1BgY5xSwk4c56mnqhEqDyOLSxVSTkYq0pStWNpvckzg4uTCnWsiMCNMakdV4Ui9ag2EC1IIIRwLjE6IMYrgpMbGxolBZUteV6lWyooekXUpy+oLpKZmdQX8xiDGogKyCSjSQq0E1MVaBog9ZxxQjG18kGBTKKwUCrFzfxdyRThQkCLcEJk"
type = 'seq'
